In [4]:
from numpy import array
import numpy

def gauss(a, b):
    a = a.copy()
    b = b.copy()
    def forward():

        def zamena(stolb):
            if a[stolb, stolb] == 0:
                stroka = stolb + 1
                for i in a[stolb + 1:,stolb]:
                    if i == 0:
                        stroka += 1
                        continue
                    else:
                        a[stroka], a[stolb] = a[stolb].copy(), a[stroka].copy()
                        b[stroka], b[stolb] = b[stolb].copy(), b[stroka].copy()
                        break
                   
        def perestanovka(stolb):
            vedus = a[stolb, stolb]
            for i in range(len(a) - stolb - 1):
                b[stolb + i + 1] = b[stolb + i + 1] - a[stolb + i + 1, stolb].copy() / vedus
                a[stolb + i + 1, stolb :] = a[stolb + i + 1, stolb :] - a[stolb, stolb :] * a[stolb + i + 1, stolb] / vedus

        for i in range(len(a) - 1):
            zamena(i)
            perestanovka(i)

    forward()
    return a, b
a = array([[2,2,5], [4,4,6], [7, 8, 10]], dtype = float)
b = array([1, 2, 3], dtype = float)
print(a)
print(b)
gauss(a, b)

[[ 2.  2.  5.]
 [ 4.  4.  6.]
 [ 7.  8. 10.]]
[1. 2. 3.]


(array([[ 2. ,  2. ,  5. ],
        [ 0. ,  1. , -7.5],
        [ 0. ,  0. , -4. ]]),
 array([ 1. , -0.5,  0. ]))